/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project2_GUI;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * CAMILLE JOYCE CARREON
 * STUDENT ID 22172806
 * PROGRAM DESIGN AND CONSTRUCTION 
 * COMP603 -  SOFTWARE CONSTRUCTION
 * PROJECT 2 ASSIGNMENT
 * 
 */
public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public SignUp() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HeaderPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BodyPanel = new javax.swing.JPanel();
        SubBodyPanel = new javax.swing.JPanel();
        SignupHeader = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        FirstNameLabel = new javax.swing.JLabel();
        firstname_textfield = new javax.swing.JTextField();
        PasswordLabel = new javax.swing.JLabel();
        password_textfield = new javax.swing.JPasswordField();
        LastNameLabel = new javax.swing.JLabel();
        lastname_textfield = new javax.swing.JTextField();
        EmployeeIDLabel = new javax.swing.JLabel();
        employeeid_textfield = new javax.swing.JTextField();
        ProceedButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ordering System - inc-READY-ble!");
        setBackground(new java.awt.Color(255, 245, 224));
        setForeground(java.awt.Color.darkGray);
        setResizable(false);

        HeaderPanel.setBackground(new java.awt.Color(199, 0, 57));
        HeaderPanel.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 55)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(242, 242, 242));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("inc-READY-ble!");
        HeaderPanel.add(jLabel1);
        jLabel1.setBounds(0, 2, 830, 70);

        BodyPanel.setBackground(new java.awt.Color(20, 30, 70));
        BodyPanel.setLayout(null);

        SubBodyPanel.setBackground(new java.awt.Color(255, 245, 224));

        SignupHeader.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        SignupHeader.setForeground(new java.awt.Color(255, 105, 105));
        SignupHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SignupHeader.setText("Sign Up");

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        FirstNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        FirstNameLabel.setText("First Name");

        firstname_textfield.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        firstname_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstname_textfieldActionPerformed(evt);
            }
        });

        PasswordLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PasswordLabel.setText("Password");

        password_textfield.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        password_textfield.setMinimumSize(new java.awt.Dimension(35, 20));
        password_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                password_textfieldActionPerformed(evt);
            }
        });

        LastNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LastNameLabel.setText("Last Name");

        lastname_textfield.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        EmployeeIDLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EmployeeIDLabel.setText("EmployeeID");

        employeeid_textfield.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        ProceedButton.setBackground(new java.awt.Color(20, 30, 70));
        ProceedButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ProceedButton.setForeground(new java.awt.Color(242, 242, 242));
        ProceedButton.setText("Proceed");
        ProceedButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ProceedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProceedButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SubBodyPanelLayout = new javax.swing.GroupLayout(SubBodyPanel);
        SubBodyPanel.setLayout(SubBodyPanelLayout);
        SubBodyPanelLayout.setHorizontalGroup(
            SubBodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SignupHeader, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(SubBodyPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(SubBodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SubBodyPanelLayout.createSequentialGroup()
                        .addComponent(EmployeeIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(189, 189, 189)
                        .addComponent(PasswordLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(password_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addGroup(SubBodyPanelLayout.createSequentialGroup()
                        .addGroup(SubBodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FirstNameLabel)
                            .addGroup(SubBodyPanelLayout.createSequentialGroup()
                                .addGap(103, 103, 103)
                                .addGroup(SubBodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(employeeid_textfield, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                    .addComponent(firstname_textfield))
                                .addGap(28, 28, 28)
                                .addComponent(LastNameLabel)))
                        .addGap(18, 18, 18)
                        .addComponent(lastname_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SubBodyPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(SubBodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SubBodyPanelLayout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SubBodyPanelLayout.createSequentialGroup()
                        .addComponent(ProceedButton, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(231, 231, 231))))
        );
        SubBodyPanelLayout.setVerticalGroup(
            SubBodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SubBodyPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(SignupHeader)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(SubBodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstname_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FirstNameLabel)
                    .addComponent(lastname_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LastNameLabel))
                .addGap(18, 18, 18)
                .addGroup(SubBodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PasswordLabel)
                    .addComponent(password_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmployeeIDLabel)
                    .addComponent(employeeid_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(ProceedButton)
                .addGap(85, 85, 85))
        );

        BodyPanel.add(SubBodyPanel);
        SubBodyPanel.setBounds(120, 90, 590, 220);

        jButton1.setBackground(new java.awt.Color(199, 0, 57));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 245, 224));
        jButton1.setText("BACK TO LOGIN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        BodyPanel.add(jButton1);
        jButton1.setBounds(625, 372, 170, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HeaderPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 830, Short.MAX_VALUE)
            .addComponent(BodyPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(HeaderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(BodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("inc-READY-ble! Ordering System - SIGNUP");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ProceedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProceedButtonActionPerformed
        try 
        {
            String firstName = firstname_textfield.getText().trim();
            String lastName = lastname_textfield.getText().trim();
            String employeeID = employeeid_textfield.getText().trim();
            String password = password_textfield.getText().trim();
            if(firstName.isEmpty() || lastName.isEmpty() || employeeID.isEmpty() || password.isEmpty())
            {
                JOptionPane.showMessageDialog(this, "Please don't leave the text fields empty. Try again.");       
            }
            else if(employeeID.length() > 5 || employeeID.length() < 5 || !employeeID.startsWith("E"))
            {
                JOptionPane.showMessageDialog(this, "Invalid Employee ID. "
                                   + "Check if you've entered a 5-character "
                                   + "employee ID with a 'E' in the beginning.");
            }
            else
            {
                Connection database = DriverManager.getConnection("jdbc:derby://localhost:1527/Employee_Accounts", "proj2", "Edatabase603");
                PreparedStatement script = database.prepareStatement("SELECT * FROM EMPLOYEE_DETAILS "
                                                            + "WHERE FIRST_NAME = ? AND LAST_NAME = ? AND EMPLOYEE_ID = ? AND PASSWORD = ?");
                script.setString(1, firstname_textfield.getText());
                script.setString(2, lastname_textfield.getText());
                script.setString(3, employeeid_textfield.getText());
                script.setString(4, String.valueOf(password_textfield.getPassword()));
                ResultSet rs = script.executeQuery();
                //If else statement to redirect to another Jframe and to inform user for invalid access due to wrong information
                if(rs.next()) 
                {
                    JOptionPane.showMessageDialog(this, "This account has already existed.");
                    firstname_textfield.setText("");
                    lastname_textfield.setText("");
                    employeeid_textfield.setText("");
                    password_textfield.setText("");
                }
                else
                    {
                    Statement script2 = database.createStatement();
                    script2.execute("INSERT INTO EMPLOYEE_DETAILS VALUES('" + employeeID + "', '" + firstName 
                                   + "', '" + lastName + "', '" + password + "', null, null, null, null)");
                    JOptionPane.showMessageDialog(this, "Account Registered. Welcome, " + firstName + " " + lastName + ".");
                    //redirecting to another Jframe (SigUp Verification)
                    SignUpVerification verification = new SignUpVerification(employeeID);
                    verification.setVisible(true);
                    this.dispose();
                    }
                
            }
        } 
        catch (SQLException e) 
        {
            Logger.getLogger(SignUp.class.getName()).log(Level.SEVERE, null, e);
        }
        
              
    }//GEN-LAST:event_ProceedButtonActionPerformed

    private void password_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_password_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_password_textfieldActionPerformed

    private void firstname_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstname_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstname_textfieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    Login login = new Login();
        this.dispose();
    login.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
                new SignUp().setBackground(Color.red);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BodyPanel;
    private javax.swing.JLabel EmployeeIDLabel;
    private javax.swing.JLabel FirstNameLabel;
    private javax.swing.JPanel HeaderPanel;
    private javax.swing.JLabel LastNameLabel;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JButton ProceedButton;
    private javax.swing.JLabel SignupHeader;
    private javax.swing.JPanel SubBodyPanel;
    private javax.swing.JTextField employeeid_textfield;
    private javax.swing.JTextField firstname_textfield;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField lastname_textfield;
    private javax.swing.JPasswordField password_textfield;
    // End of variables declaration//GEN-END:variables
}
